### ISSUE TITLE
cant host 

### ISSUE THREAD

**Issue by odoylerulz26** [CnCNet/cncnet-yr-client-package#103]
I cant host a game and even if my friend tries to host the game as well only one of us load in and the other does not load in at all. Then one of us will load into the map and the other will be left at the lobby screen.

**Comment by devo1929** [comment]
> I cant host a game and even if my friend tries to host the game as well only one of us load in and the other does not load in at all. Then one of us will load into the map and the other will be left at the lobby screen.

Sounds like you need to try a different tunnel. The person hosting should have a Change Tunnel button at the bottom of the lobby screen.

**Comment by odoylerulz26** [comment]
we have both tried multiple different tunnels and it doesn't fix the problem. we have only ever been able to play 2 games together as one of us as host but we can play together if someone else hosts the lobby.

**Comment by Belonit** [comment]
I'm closing this Issues because it's outdated
