### ISSUE TITLE
freezing game

### ISSUE THREAD

**Issue by snickers007** [CnCNet/cncnet-yr-client-package#108]
hello the game freezing at random intervals , my windows 10

**Comment by GrantBartlett** [comment]
> hello the game freezing at random intervals , my windows 10

You tried these steps? https://github.com/CnCNet/cncnet-yr-client-package/issues/108#issue-1130559349

**Comment by snickers007** [comment]
steps ?

**Comment by GrantBartlett** [comment]
> steps ?

https://forums.cncnet.org/topic/6866-frequently-asked-questions/#comment-53290

 

- [Install the CnCNet client](https://cncnet.org/red-alert-2) 
- This will look for your existing game directory.
- Once installed run CnCNetYRLauncher.exe or the shortcut supplied.
- Click "Options"
- Select "Display" and under the render options, select a new renderer. Commonly, "Automatic", "CNC-DRRAW" or "TS-DDRAW" works best.
- Click Save, and launch Skirmish. 
- Play a game with the AI. If the gameplay is fast then this renderer will likely be the best for you.
- If it hasn't worked, repeat from step 5 until you find a renderer that works best with your system.
- Failing the above, ensure your video drivers are up-to-date. You are running a suitable resolution the game can handle.

**Comment by Belonit** [comment]
I'm closing this Issues because it's outdated
