### ISSUE TITLE
Trainers not working?

### ISSUE THREAD

**Issue by Porkechebure** [CnCNet/cncnet-yr-client-package#120]
Hello,
Me and my friend used to play in LAN parties with infinite money.
Trainers don't work anymore.
Why?
The base yuri exe and dlls changed version with this thing?

**Comment by CC-RaVaGe** [comment]
It's due to added anti-cheat for competitive players.

**Comment by CC-RaVaGe** [comment]
Not possible, otherwise people would remove it for ranked as well and we don't want that.

**Comment by Porkechebure** [comment]
> Not possible, otherwise people would remove it for ranked as well and we don't want that.

Then fix online, it doesn't work. When one connects, the other player comes and we get both disconnected
