### ISSUE TITLE
60 fps is now too fast

### ISSUE THREAD

**Issue by sand3r** [CnCNet/cncnet-yr-client-package#126]
Hi,

In the new client 8.13.1. when selecting the Fastest (60 fps) gamespeed it is too fast now. Earlier I played on 60 fps just fine (8.12) but now it is unplayable. 45 fps is fine, but still too slow compared to the gamespeed of 60 fps I liked from 8.12. Is this a known issue?

If I remember correctly, in 8.12, there was next to 60 fps also one faster option.

Edit: checked in 8.12, this is the game speed selection there:
![image](https://user-images.githubusercontent.com/564494/165948080-9d0760bb-6a37-4d71-8f28-68d2ad0a87a8.png)

**Comment by alanachtenberg** [comment]
Seeing the same issue. Build speed is near instant on fastest setting.

**Comment by rursache** [comment]
same issue here, as im never playing online, ill downgrade

**Comment by devo1929** [comment]
It's simply a mislabel issue in that is shows the incorrect FPS with each label. There was an overhaul to the way the UI is built in 8.13 that caused this to happen. In the newer versions, simply choose "Faster (45 FPS)". It's the same as "Faster (60 FPS)" in the older version.

**Comment by devo1929** [comment]
I made a change to fix this for the skirmish lobby. It should be fixed in the next release, 8.17.5 or later.
