### ISSUE TITLE
No Longer OPEN-Sourced?

### ISSUE THREAD

**Issue by Daiki9527** [CnCNet/cncnet-yr-client-package#142]
DTA Client Version has been updated to 2.10.3.0

YR's is 2.8.0.0

But Open Sourced version is 2.6.11.0.

Is the client source no longer open? :(

**Comment by devo1929** [comment]
All of these assembly versions you're referencing are from the xna client repository. Not this one. This repo is simply a wrapper for the YR configuration files to use the shared XNA client.

https://github.com/CnCNet/xna-cncnet-client

`2.6.11.0` is from the master branch (from the repo above).
`2.8.0.0` is from the develop branch.
I'm not sure where you got `2.10.3.0` from.
