### ISSUE TITLE
How to disable menu theme music?

### ISSUE THREAD

**Issue by TRPB** [CnCNet/cncnet-yr-client-package#17]
When running on Wine in Linux, cncnet crashes, it seems to be due to playing the wma music file. Is there any way to just turn this off? I can't find a reference to where this is loaded. If I remove the file, it doesn't crash but it hangs instead. 

I managed to get it working initially by copying "Allied Theme" as "Yuri Theme" but as soon as I updated from the installer's version to 6.5 in cncnet, this workaround didn't work any longer. 

I've tried installing codecs, windows media player, wmfdist and various other packages but this wma file just causes the crash. Annoyingly it seems to be the only thing preventing cncnet working, I can live without the music if it's possible to turn it off. 

[client.log](https://github.com/CnCNet/cncnet-yr-client-package/files/4617856/client.log)

**Comment by OrangeIsALie** [comment]
Try the audio options in Main Menu > Options > Audio
Uncheck everything for music and turn the music volume to 0.

**Comment by ThomasShaped** [comment]
Is there a workaround for this? Am running into the same problem. Can get the launcher to boot after first install (and even disable the music) but after updating the client I'm still running into this.

**Comment by Belonit** [comment]
I'm closing this Issues because it's outdated
