### ISSUE TITLE
Yuri's Revenge crashing mid-game

### ISSUE THREAD

**Issue by jonathan84clark** [CnCNet/cncnet-yr-client-package#178]
Hello,

Today I noticed an issue where C&C net Yuri's revenge has been crashing mid-game. This happened to me once when I was playing with my son and two more times when I was playing by myself. I can't get through a game without it crashing. The first time I noticed the crash was in a multiplayer game, the second and third time it crashed were during a Skirmish. 

I was wondering if you guys could look into this.

Here is the end of the client log, just before the crash:
```
21.10. 22:37:26.814    Discord: Pipe Connection Failed. Could not connect to pipe #-1
21.10. 22:38:37.824    Discord: Pipe Connection Failed. Could not connect to pipe #-1
21.10. 22:39:48.837    Discord: Pipe Connection Failed. Could not connect to pipe #-1
21.10. 22:40:59.847    Discord: Pipe Connection Failed. Could not connect to pipe #-1
21.10. 22:42:10.845    Discord: Pipe Connection Failed. Could not connect to pipe #-1
21.10. 22:43:21.861    Discord: Pipe Connection Failed. Could not connect to pipe #-1
21.10. 22:44:24.820    GameProcessLogic: Process exited.
21.10. 22:44:25.006    InitGraphicsMode: 1360x768
21.10. 22:44:25.019    GameProcessExited: Parsing statistics.
21.10. 22:44:25.020    Parsing game statistics.
21.10. 22:44:25.022    DTAStatisticsParser: Failed to read statistics: the log file does not exist.
21.10. 22:44:25.022    GameProcessExited: Adding match to statistics.
21.10. 22:44:25.024    Writing game info to statistics file.
21.10. 22:44:25.026    Finished writing statistics.
21.10. 22:44:25.051    Saved Games directory not found!
21.10. 22:44:32.869    Discord: Pipe Connection Failed. Could not connect to pipe #-1
21.10. 22:44:37.615    Exiting.
21.10. 22:44:37.615    Saving friend list.
21.10. 22:44:37.616    Saving ignore list.
21.10. 22:44:37.617    Saving recent list.
```
The full log is attached. I am running the latest version 8.18.1. The installed version on my PC is from Origin. Please let me know if you need any additional information. 
Any help here would be great.

Thanks,

Jonathan L Clark

[client.log](https://github.com/CnCNet/cncnet-yr-client-package/files/9843670/client.log)

**Comment by devo1929** [comment]
Unfortunately, that log file will not help us. The client executable (the one we develop and maintain) is not the same as the running game executable (the one we do NOT develop or maintain).

Can you provide some more details on the game? What map were you playing on? Any mods installed?
