### ISSUE TITLE
Save CnCnet game settings

### ISSUE THREAD

**Issue by PablosScripts** [CnCNet/cncnet-yr-client-package#20]
I have to reconfigure these settings every time I boot up CnCnet for a new game. Is it possible to save them?

![image](https://user-images.githubusercontent.com/22415147/82174471-2d804c80-9914-11ea-8f45-9968d44f35f4.png)

**Comment by IshaySela** [comment]
I'm not a developer, but as far as I know there is no way.

**Comment by DirkTervish** [comment]
I second this. Maybe there is a way? The default values come from somewhere. Further, is the launcher the RA2 code or is it the CnCNet's?

**Comment by Saint146** [comment]
@PablosScripts , to save these settings you have to add a line to the file `Resources/ClientDefinitions.ini` under your client folder:
`SaveSkirmishGameOptions=yes`

Was struggling with it too, had to debug the client myself to discover this.

Maybe it would be a good idea to turn this setting on by default (I mean, why not?)

**Comment by Belonit** [comment]
I'm closing this Issues because it's outdated
