### ISSUE TITLE
LAN not working?

### ISSUE THREAD

**Issue by Hassanshin** [CnCNet/cncnet-yr-client-package#21]
Cant find my friend in lan list.. a direct link connect needed..

**Comment by GrantBartlett** [comment]
Make sure you're both on the same version of the client. Also make sure any firewalls allow the client to function and are not being blocked.

Alternatively try using online as a test with your friend too.

**Comment by Hassanshin** [comment]
we able to connect online, but in LAN we cant see ech other room.. so i think i need a direct ip connect for lan

**Comment by Hassanshin** [comment]
uninstall vpn, resetting network adapter, and it's working
