### ISSUE TITLE
Configure Ares/Phobos default game options

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/cncnet-yr-client-package#291]
1. Configure Ares/Phobos default game options
2. Also add additional UI checkboxes to Game tab. 

![Image](https://github.com/CnCNet/cncnet-yr-client-package/assets/6104940/92f915d7-8a72-439a-92a2-6ad4b339549a)

List still WIP

- [x] Show Building Placement Preview - Off by default
- [x] Quick Exit - ON by default

**Comment by Metadorius** [comment]
@Belonit selection priority filtering should also be added

**Comment by Belonit** [comment]
@Metadorius This change affects the gameplay, I would prefer to have a priority filter in another pr

**Comment by Metadorius** [comment]
@Belonit IMO UX feature like this is not gameplay altering, and besides we already add a new hotkey (and CnCNet already did this, maybe not in YR but IIRC some hotkeys were added).
