### ISSUE TITLE
Killed aircraft spawn surviving pilots

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/cncnet-yr-client-package#313]
It's nice, but needs removing for Beta.

**Reported by Discord user: Madness**
https://github.com/CnCNet/cncnet-yr-client-package/assets/6104940/3e9262a5-437a-4387-9023-1490d2c1ea20

**Comment by Belonit** [comment]
This problem affects not only the Harrier, but the entire aircraft fleet
