### ISSUE TITLE
I get prompted to upgrade to non-existent version

### ISSUE THREAD

**Issue by ibonobo** [CnCNet/cncnet-yr-client-package#34]
The latest version here is 7.5 but I get prompted to upgrade to version 7.7 which does not exist. Clicking on Changelog takes me here.
![ScreenshotRA2CNCy2021-04-03_7](https://user-images.githubusercontent.com/679170/113490561-dd14cd80-9498-11eb-8ccb-9fa8892627c9.jpg)

**Comment by ibonobo** [comment]
also, can't load saved game files

**Comment by pzhlkj6612** [comment]
Hi.

<br>

> version 7.7 which does not exist.

Well, it does exist. The updater will check update info on `http://downloads.cncnet.org/updates/yr/version` , you can see the version is 7.7 .

```ini
[DTA]
Version=7.7

[FileVersions]
...
```

I don't know why the new releases have not been published here. Maybe the maintainer has no spare time, I guess.

---

> also, can't load saved game files

I'm not familiar with this, but I suggest you open an issue on [CnCNet/xna-cncnet-client](https://github.com/CnCNet/xna-cncnet-client) with detailed reproduce steps and attach your `<GameRootDir>/Client/client.log` file as well.

**Comment by pzhlkj6612** [comment]
> also, can't load saved game files
> > open an issue on CnCNet/xna-cncnet-client ...

Wait... I'm sorry. This should not be reported to CnCNet Client repo, but here.

if #18 is not the same as yours, you can open a new issue with detailed reproduce steps and screenshots.

**Comment by ibonobo** [comment]
> > also, can't load saved game files
> > > open an issue on CnCNet/xna-cncnet-client ...
> 
> Wait... I'm sorry. This should not be reported to CnCNet Client repo, but here.
> 
> if #18 is not the same as yours, you can open a new issue with detailed reproduce steps and screenshots.

Yes, it's the same, thanks.

**Comment by ibonobo** [comment]
> > version 7.7 which does not exist.
> 
> Well, it does exist. The updater will check update info on `http://downloads.cncnet.org/updates/yr/version` , you can see the version is 7.7 .
> 
> ```ini
> [DTA]
> Version=7.7
> 
> [FileVersions]
> ...
> ```
> 
> I don't know why the new releases have not been published here. Maybe the maintainer has no spare time, I guess.
> 

Can we have a look at the code or changelog (7.6, 7.7) elsewhere?

**Comment by pzhlkj6612** [comment]
Hi @Metadorius , can I ask you why no new git tags are added to this repository? Thanks.

**Comment by Metadorius** [comment]
> Hi @Metadorius , can I ask you why no new git tags are added to this repository? Thanks.

Hey Mozi, good catch, we actually forgot to. We'll add them soon, thanks.

**Comment by pzhlkj6612** [comment]
> We'll add them soon, thanks.

That's okay, and thank you for your reply.

I think it would be better if you guys tag XNA Client as well. Otherwise, normal users cannot get any "update" about the project on GitHub.
