### ISSUE TITLE
The mission is failed if the hero enters the vehicle

### ISSUE THREAD

**Issue by Belonit** [CnCNet/cncnet-yr-client-package#349]
This problem occurs at least in the mission `Allied Mission 8 - Free Gateway`

**Comment by Belonit** [comment]
The problem is that when calling `TechnoClass::Limbo`, the unit counter for the house is updated. But in RA2 maps there is a separate house for heroes, and the trigger is triggered when the house loses all its units. I should change this behavior in RA2Mode in `yrpp-spawner`, but have not yet figured out how to do it correctly

**Comment by CnCRAZER** [comment]
If this is the only ra2 mission with this problem, maybe it would be more simple to have a mapper adjust the triggers and such in a way where the player wouldn't notice. 

Unless we are opposed to changing anything campaign related.

**Comment by Belonit** [comment]
> If this is the only ra2 mission with this problem, maybe it would be more simple to have a mapper adjust the triggers and such in a way where the player wouldn't notice.
> 
> Unless we are opposed to changing anything campaign related.

No, this problem is present in all Ra2 missions.  I've already found a clue and will update `yrpp-spawner` soon to fix this

**Comment by Belonit** [comment]
Okay, this issue should be fixed in the latest beta
