### ISSUE TITLE
Can I come up with my own solution for Yuri Rebalance Patch.ini?

### ISSUE THREAD

**Issue by XMxmx111** [CnCNet/cncnet-yr-client-package#354]
This configuration file doesn't appear to have been updated in three years, and I don't think it's reached a completed state. Has it been put on hold? Can I submit some minor changes to it? If I get permission, I will submit each pull request carefully, describe each change I make in detail, and welcome differing opinions.

**Comment by alexp8** [comment]
sure, the team could review each change

**Comment by XMxmx111** [comment]
Thanks. By the way, is it better for a team review to submit a separate merge request for each change, or multiple changes together?

**Comment by alexp8** [comment]
each separately could be better
