### ISSUE TITLE
How to get the perfect preview image???

### ISSUE THREAD

**Issue by ismail-doitbig** [CnCNet/cncnet-yr-client-package#360]
I have been trying different resolutions for the preview image but i cant for the love of god get a perfect image.

What is the ratio or resolution that I should aim for?

Any docs on this?

**Comment by CnCRAZER** [comment]
Well, the preview section of the client is a rectangle that has a larger X value than a Y value. Perhaps trial and error is best until you're able to get something that satisfies you. 

Also, something like this is probably best posted in the modding-mapping section of the cncnet discord server. More likely to be seen.

**Comment by CnC-RaVaGe** [comment]
![image](https://github.com/user-attachments/assets/a7ae8892-6402-408d-bea5-e9773c266707)
As small as file size as you can get. It will never match the pixel ratio 1:1 as the client does some weird stretching or scaling to suit the desktop (when in fullscreen) or your set client resolution (when in windowed mode).

@devo1929  can close this.
