### ISSUE TITLE
Can't upgrade from 7.7 to 8.1, File Already Exists

### ISSUE THREAD

**Issue by ThreeSevenths** [CnCNet/cncnet-yr-client-package#37]
Attempted to do the prompted upgrade from 7.7 to 8.1, and after downloading, received an error that a file already exists. 

Workaround: Reinstall Client and Update from base to 8.1

**Comment by fadykhayrat88** [comment]
i download [CnCNet ](https://cncnet.org/red-alert-2) again and install it then i updated it and it is work with me

**Comment by ThreeSevenths** [comment]
> i download [CnCNet ](https://cncnet.org/red-alert-2) again and install it then i updated it and it is work with me

Yeah that's what I ended up doing too. I haven't had to do that before though, and I think it's a bug with the install script.
