### ISSUE TITLE
Selecting position 9 on Valley of the Exiles Crashes game

### ISSUE THREAD

**Issue by ThreeSevenths** [CnCNet/cncnet-yr-client-package#38]
On this map, you're able to select position 9 which will crash a multiplayer lobby.

![image](https://user-images.githubusercontent.com/1298072/116837872-2476a280-ab9a-11eb-9090-c6dbb8e0ef37.png)

[ClientCrashLog_2021_05_02_22_56.txt](https://github.com/CnCNet/cncnet-yr-client-package/files/6412727/ClientCrashLog_2021_05_02_22_56.txt)

**Comment by alexp8** [comment]
Thank you for finding this issue, I have not seen this before haha!
We will address this in the next update.

![valley](https://user-images.githubusercontent.com/11843268/117034744-76154f00-acb8-11eb-8b36-3b4adeaccbc3.PNG)

**Comment by alexp8** [comment]
I have the fix in place, will push in the next update @ThreeSevenths
