### ISSUE TITLE
8.62.0 update has stopped me from being able to play online

### ISSUE THREAD

**Issue by OA123341** [CnCNet/cncnet-yr-client-package#380]
8.62.0 update has stopped me from being able to play online. I update the game as need it or when it asks me to but it got stuck here and not updating nor can i play online anymore
need help please

**Comment by alexp8** [comment]
can you add a screenshot

**Comment by OA123341** [comment]
![Screenshot 2024-10-29 234726](https://github.com/user-attachments/assets/615cd852-3ab8-4a01-a75b-c216e75d385e)
![Screenshot 2024-10-29 234539](https://github.com/user-attachments/assets/e8c108b7-61ca-4d3f-a84c-5f6e12e62b35)

i get stuck here

**Comment by brichardson1991** [comment]
It's waiting for the client to exit. Can you force exit the client and see if it continues.

**Comment by GrantBartlett** [comment]
If this doesn't work can you use the latest installer and see if that helps. https://github.com/CnCNet/cncnet-yr-client-package/releases/download/yr-8.62/CnCNet5_YR_Installer_8.62.0.exe

**Comment by OA123341** [comment]
it worked! thank you so much!
